"use client";
import { useEffect, useMemo, useState } from "react";
import { Area, AreaChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowDownRight, ArrowUpRight, CalendarDays, ChevronDown, Download, QrCode, Star, TrendingUp, Trophy } from "lucide-react";
import Link from "next/link";
import AccountMenu from "./account-menu";

const periods = ["Last 7 days", "Last 30 days", "Current month", "Previous month", "Last 3 months"];
function Card({ title, value, note, positive = true, icon }: { title:string; value:string; note:string; positive?:boolean; icon:React.ReactNode }) {
 return <div className="card kpi"><div className="kpi-head"><span>{title}</span><i>{icon}</i></div><strong>{value}</strong><p className={positive ? "up" : "down"}>{positive ? <ArrowUpRight/> : <ArrowDownRight/>}{note} <em>vs previous period</em></p></div>;
}
function ChartCard({ title, subtitle, children }: { title:string; subtitle:string; children:React.ReactNode }) { return <section className="card chart-card"><div><h2>{title}</h2><p>{subtitle}</p></div>{children}</section>; }
export default function Dashboard() {
 const [period, setPeriod] = useState("Last 30 days"); const [open, setOpen] = useState(false); const [business,setBusiness]=useState("Your business"); const [metrics,setMetrics]=useState<{rating:number|null;totalReviews:number|null;newReviews:number|null;ratingChange:number|null;qrScans:number}>({rating:null,totalReviews:null,newReviews:null,ratingChange:null,qrScans:0}); const [scanPoints,setScanPoints]=useState<{date:string;value:number}[]>([]); const [reviewPoints,setReviewPoints]=useState<{date:string;value:number}[]>([]); const [ratingPoints,setRatingPoints]=useState<{date:string;value:number}[]>([]);
 useEffect(()=>{const token=localStorage.getItem("reviewflow_token");if(!token)return;const headers={Authorization:`Bearer ${token}`};fetch(`/api/business`,{headers}).then(r=>r.ok?r.json():null).then(b=>{if(b?.name){setBusiness(b.name);localStorage.setItem("reviewflow_business",b.name)}}).catch(()=>{});fetch(`/api/analytics/overview`,{headers}).then(r=>r.ok?r.json():null).then(x=>{if(x)setMetrics(x)}).catch(()=>{});fetch(`/api/analytics/scans`,{headers}).then(r=>r.ok?r.json():null).then(x=>setScanPoints(Array.isArray(x)?x:[])).catch(()=>{});fetch(`/api/analytics/reviews`,{headers}).then(r=>r.ok?r.json():null).then(x=>setReviewPoints(Array.isArray(x)?x:[])).catch(()=>{});fetch(`/api/analytics/rating`,{headers}).then(r=>r.ok?r.json():null).then(x=>setRatingPoints(Array.isArray(x)?x:[])).catch(()=>{});},[]);
 const greeting = useMemo(() => new Date().getHours() < 12 ? "Good morning" : "Good afternoon", []);
 return <main className="shell"><aside><Link className="brand" href="/dashboard"><span>✦</span> reviewflow</Link><nav><Link className="active" href="/dashboard"><TrendingUp/>Overview</Link><Link href="/qr-code"><QrCode/>QR code</Link><Link href="/benchmark"><Trophy/>Local benchmark</Link></nav><div className="side-bottom"><div className="help">?<span><b>Need a hand?</b><small>Visit our help centre</small></span></div><AccountMenu business={business}/></div></aside>
 <div className="content"><header><div><p className="eyebrow">OVERVIEW</p><h1>{greeting}, {business}</h1><p className="muted">Here&apos;s how your reviews are growing.</p></div><Link className="button" href="/qr-code"><QrCode/> Manage QR code</Link></header>
 <div className="toolbar"><div className="period"><CalendarDays/><button onClick={()=>setOpen(!open)}>{period}<ChevronDown/></button>{open && <div className="menu">{periods.map(p=><button key={p} onClick={()=>{setPeriod(p);setOpen(false)}}>{p}</button>)}<button>Custom range…</button></div>}</div><button className="icon-button"><Download/></button></div>
 <section className="kpis"><Card title="Current rating" value={metrics.rating == null ? "—" : metrics.rating.toFixed(1)} note={metrics.rating == null ? "No verified data" : "Verified rating"} icon={<Star/>}/><Card title="Total reviews" value={metrics.totalReviews == null ? "—" : metrics.totalReviews.toLocaleString()} note={metrics.totalReviews == null ? "No verified data" : "Verified count"} icon={<TrendingUp/>}/><Card title="QR scans" value={metrics.qrScans.toLocaleString()} note={metrics.qrScans?"Live scan data":"No scans yet"} icon={<QrCode/>}/><Card title="Rating change" value={metrics.ratingChange == null ? "—" : `${metrics.ratingChange >= 0 ? "+" : ""}${metrics.ratingChange.toFixed(1)}`} note={metrics.ratingChange == null ? "No history yet" : "Since period start"} icon={<ArrowUpRight/>}/></section><p style={{fontSize:12,color:"#75602b",margin:"14px 0"}}>{metrics.rating == null ? "Add a verified rating and review count to see Google metrics." : "Google metrics are manually verified until Google syncing is enabled. QR scan figures are recorded by ReviewFlow."}</p>
 <section className="chart-grid"><ChartCard title="Review growth" subtitle="Verified total Google reviews over time"><ResponsiveContainer width="100%" height={238}><AreaChart data={reviewPoints.map(x=>({date:x.date,reviews:x.value}))}><defs><linearGradient id="review" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#5c68e8" stopOpacity=".22"/><stop offset="1" stopColor="#5c68e8" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="#edf0f6"/><XAxis dataKey="date" tickLine={false} axisLine={false}/><YAxis allowDecimals={false} tickLine={false} axisLine={false}/><Tooltip/><Area type="monotone" dataKey="reviews" stroke="#5966dc" strokeWidth={2.5} fill="url(#review)"/></AreaChart></ResponsiveContainer></ChartCard>
 <ChartCard title="Rating trend" subtitle="Verified Google rating over time"><ResponsiveContainer width="100%" height={238}><LineChart data={ratingPoints.map(x=>({date:x.date,rating:x.value}))}><CartesianGrid vertical={false} stroke="#edf0f6"/><XAxis dataKey="date" tickLine={false} axisLine={false}/><YAxis domain={[0,5]} tickLine={false} axisLine={false}/><Tooltip/><Line type="stepAfter" dataKey="rating" stroke="#f2a83a" strokeWidth={2.5} dot={{fill:"#f2a83a",r:3}}/></LineChart></ResponsiveContainer></ChartCard></section>
 <section className="card scan-chart"><div className="chart-heading"><div><h2>QR scans over time</h2><p>How many people scanned your review code.</p></div><span className="legend"><i/> QR scans</span></div><ResponsiveContainer width="100%" height={210}><AreaChart data={scanPoints.map(x=>({date:x.date,scans:x.value}))}><CartesianGrid vertical={false} stroke="#edf0f6"/><XAxis dataKey="date" tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false}/><Tooltip/><Area type="monotone" dataKey="scans" stroke="#28a784" strokeWidth={2.5} fill="#d8f1ea"/></AreaChart></ResponsiveContainer></section>
 <section className="comparison"><div><p className="eyebrow">PERIOD COMPARISON</p><h2>How you&apos;re doing vs. last period</h2></div><div className="compare-grid"><div><small>RATING</small><b>{metrics.rating == null ? "—" : metrics.rating.toFixed(1)}</b><p>{metrics.rating == null ? "No verified data" : "Verified rating"}</p></div><div><small>NEW REVIEWS</small><b>{metrics.newReviews == null ? "—" : metrics.newReviews}</b><p>{metrics.newReviews == null ? "No history yet" : "In this period"}</p></div><div><small>QR SCANS</small><b>{metrics.qrScans}</b><p>{metrics.qrScans ? "Live scan data" : "No scans yet"}</p></div><div><small>REVIEW GROWTH</small><b>{metrics.totalReviews == null ? "—" : metrics.totalReviews}</b><p>{metrics.totalReviews == null ? "No verified data" : "Current total"}</p></div></div></section></div></main>;
}
