package com.reviewflow.web;
import com.reviewflow.domain.*;import com.reviewflow.repo.*;import jakarta.validation.constraints.*;import org.springframework.http.*;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/api/business") public class BusinessController {private final BusinessRepository businesses;private final QrCodeRepository codes;public BusinessController(BusinessRepository b,QrCodeRepository q){businesses=b;codes=q;}record BusinessInput(@NotBlank String name,@NotBlank @Pattern(regexp="https?://.+",message="Enter a valid Google review URL") String googleReviewUrl){} record BusinessResponse(String id,String name,String slug,String googleReviewUrl,String trackingUrl){}
 private UUID owner(Authentication a){return (UUID)a.getPrincipal();} private BusinessResponse dto(Business b){QrCode q=codes.findFirstByBusinessIdAndActiveTrue(b.id).orElse(null);return new BusinessResponse(b.id.toString(),b.name,b.slug,b.googleReviewUrl,q==null?null:"/r/"+q.trackingSlug);}
 @GetMapping public BusinessResponse get(Authentication a){return dto(businesses.findFirstByUserId(owner(a)).orElseThrow(()->new org.springframework.web.server.ResponseStatusException(HttpStatus.NOT_FOUND,"Complete onboarding to create your business.")));}
 @PostMapping public ResponseEntity<BusinessResponse> create(@RequestBody @jakarta.validation.Valid BusinessInput in,Authentication a){if(businesses.findFirstByUserId(owner(a)).isPresent())throw new org.springframework.web.server.ResponseStatusException(HttpStatus.CONFLICT,"This MVP supports one visible location.");Business b=new Business();b.userId=owner(a);b.name=in.name();b.googleReviewUrl=in.googleReviewUrl();b.slug=slug(in.name());businesses.save(b);return ResponseEntity.status(HttpStatus.CREATED).body(dto(b));}
 @PutMapping public BusinessResponse update(@RequestBody @jakarta.validation.Valid BusinessInput in,Authentication a){Business b=businesses.findFirstByUserId(owner(a)).orElseThrow();b.name=in.name();b.googleReviewUrl=in.googleReviewUrl();b.updatedAt=java.time.Instant.now();return dto(businesses.save(b));}
 @PostMapping("/qr") public Map<String,String> qr(Authentication a){Business b=businesses.findFirstByUserId(owner(a)).orElseThrow();QrCode q=codes.findFirstByBusinessIdAndActiveTrue(b.id).orElseGet(()->{QrCode x=new QrCode();x.businessId=b.id;x.trackingSlug=b.slug;x.active=true;return codes.save(x);});return Map.of("trackingUrl","/r/"+q.trackingSlug,"slug",q.trackingSlug);}
 private String slug(String name){String s=name.toLowerCase().replaceAll("[^a-z0-9]+","-").replaceAll("(^-|-$)","");return s+"-"+UUID.randomUUID().toString().substring(0,6);}}
